import { ElementData, ElementSymbol } from './types';

// Periodic table with grid positions and neon color categories
export const ELEMENTS: ElementData[] = [
  // Period 1
  { symbol: 'H', name: 'Hydrogen', number: 1, mass: 1.008, category: 'nonmetal', row: 1, col: 1, color: '#00f0ff' },
  { symbol: 'He', name: 'Helium', number: 2, mass: 4.003, category: 'noble_gas', row: 1, col: 18, color: '#b000ff' },
  // Period 2
  { symbol: 'Li', name: 'Lithium', number: 3, mass: 6.941, category: 'alkali_metal', row: 2, col: 1, color: '#ff0040' },
  { symbol: 'Be', name: 'Beryllium', number: 4, mass: 9.012, category: 'alkaline_earth', row: 2, col: 2, color: '#ff6b00' },
  { symbol: 'B', name: 'Boron', number: 5, mass: 10.81, category: 'metalloid', row: 2, col: 13, color: '#00ff88' },
  { symbol: 'C', name: 'Carbon', number: 6, mass: 12.011, category: 'nonmetal', row: 2, col: 14, color: '#00f0ff' },
  { symbol: 'N', name: 'Nitrogen', number: 7, mass: 14.007, category: 'nonmetal', row: 2, col: 15, color: '#00f0ff' },
  { symbol: 'O', name: 'Oxygen', number: 8, mass: 15.999, category: 'nonmetal', row: 2, col: 16, color: '#00f0ff' },
  { symbol: 'F', name: 'Fluorine', number: 9, mass: 18.998, category: 'halogen', row: 2, col: 17, color: '#ffff00' },
  { symbol: 'Ne', name: 'Neon', number: 10, mass: 20.180, category: 'noble_gas', row: 2, col: 18, color: '#b000ff' },
  // Period 3
  { symbol: 'Na', name: 'Sodium', number: 11, mass: 22.990, category: 'alkali_metal', row: 3, col: 1, color: '#ff0040' },
  { symbol: 'Mg', name: 'Magnesium', number: 12, mass: 24.305, category: 'alkaline_earth', row: 3, col: 2, color: '#ff6b00' },
  { symbol: 'Al', name: 'Aluminum', number: 13, mass: 26.982, category: 'post_transition', row: 3, col: 13, color: '#00ccff' },
  { symbol: 'Si', name: 'Silicon', number: 14, mass: 28.086, category: 'metalloid', row: 3, col: 14, color: '#00ff88' },
  { symbol: 'P', name: 'Phosphorus', number: 15, mass: 30.974, category: 'nonmetal', row: 3, col: 15, color: '#00f0ff' },
  { symbol: 'S', name: 'Sulfur', number: 16, mass: 32.065, category: 'nonmetal', row: 3, col: 16, color: '#00f0ff' },
  { symbol: 'Cl', name: 'Chlorine', number: 17, mass: 35.453, category: 'halogen', row: 3, col: 17, color: '#ffff00' },
  { symbol: 'Ar', name: 'Argon', number: 18, mass: 39.948, category: 'noble_gas', row: 3, col: 18, color: '#b000ff' },
  // Period 4
  { symbol: 'K', name: 'Potassium', number: 19, mass: 39.098, category: 'alkali_metal', row: 4, col: 1, color: '#ff0040' },
  { symbol: 'Ca', name: 'Calcium', number: 20, mass: 40.078, category: 'alkaline_earth', row: 4, col: 2, color: '#ff6b00' },
  { symbol: 'Sc', name: 'Scandium', number: 21, mass: 44.956, category: 'transition_metal', row: 4, col: 3, color: '#ff6b00' },
  { symbol: 'Ti', name: 'Titanium', number: 22, mass: 47.867, category: 'transition_metal', row: 4, col: 4, color: '#ff6b00' },
  { symbol: 'V', name: 'Vanadium', number: 23, mass: 50.942, category: 'transition_metal', row: 4, col: 5, color: '#ff6b00' },
  { symbol: 'Cr', name: 'Chromium', number: 24, mass: 51.996, category: 'transition_metal', row: 4, col: 6, color: '#ff6b00' },
  { symbol: 'Mn', name: 'Manganese', number: 25, mass: 54.938, category: 'transition_metal', row: 4, col: 7, color: '#ff6b00' },
  { symbol: 'Fe', name: 'Iron', number: 26, mass: 55.845, category: 'transition_metal', row: 4, col: 8, color: '#ff6b00' },
  { symbol: 'Co', name: 'Cobalt', number: 27, mass: 58.933, category: 'transition_metal', row: 4, col: 9, color: '#ff6b00' },
  { symbol: 'Ni', name: 'Nickel', number: 28, mass: 58.693, category: 'transition_metal', row: 4, col: 10, color: '#ff6b00' },
  { symbol: 'Cu', name: 'Copper', number: 29, mass: 63.546, category: 'transition_metal', row: 4, col: 11, color: '#ff6b00' },
  { symbol: 'Zn', name: 'Zinc', number: 30, mass: 65.380, category: 'transition_metal', row: 4, col: 12, color: '#ff6b00' },
  { symbol: 'Ga', name: 'Gallium', number: 31, mass: 69.723, category: 'post_transition', row: 4, col: 13, color: '#00ccff' },
  { symbol: 'Ge', name: 'Germanium', number: 32, mass: 72.640, category: 'metalloid', row: 4, col: 14, color: '#00ff88' },
  { symbol: 'As', name: 'Arsenic', number: 33, mass: 74.922, category: 'metalloid', row: 4, col: 15, color: '#00ff88' },
  { symbol: 'Se', name: 'Selenium', number: 34, mass: 78.960, category: 'nonmetal', row: 4, col: 16, color: '#00f0ff' },
  { symbol: 'Br', name: 'Bromine', number: 35, mass: 79.904, category: 'halogen', row: 4, col: 17, color: '#ffff00' },
  { symbol: 'Kr', name: 'Krypton', number: 36, mass: 83.798, category: 'noble_gas', row: 4, col: 18, color: '#b000ff' },
  // Period 5
  { symbol: 'Rb', name: 'Rubidium', number: 37, mass: 85.468, category: 'alkali_metal', row: 5, col: 1, color: '#ff0040' },
  { symbol: 'Sr', name: 'Strontium', number: 38, mass: 87.620, category: 'alkaline_earth', row: 5, col: 2, color: '#ff6b00' },
  { symbol: 'Y', name: 'Yttrium', number: 39, mass: 88.906, category: 'transition_metal', row: 5, col: 3, color: '#ff6b00' },
  { symbol: 'Zr', name: 'Zirconium', number: 40, mass: 91.224, category: 'transition_metal', row: 5, col: 4, color: '#ff6b00' },
  { symbol: 'Nb', name: 'Niobium', number: 41, mass: 92.906, category: 'transition_metal', row: 5, col: 5, color: '#ff6b00' },
  { symbol: 'Mo', name: 'Molybdenum', number: 42, mass: 95.960, category: 'transition_metal', row: 5, col: 6, color: '#ff6b00' },
  { symbol: 'Tc', name: 'Technetium', number: 43, mass: 98.000, category: 'transition_metal', row: 5, col: 7, color: '#ff6b00' },
  { symbol: 'Ru', name: 'Ruthenium', number: 44, mass: 101.07, category: 'transition_metal', row: 5, col: 8, color: '#ff6b00' },
  { symbol: 'Rh', name: 'Rhodium', number: 45, mass: 102.91, category: 'transition_metal', row: 5, col: 9, color: '#ff6b00' },
  { symbol: 'Pd', name: 'Palladium', number: 46, mass: 106.42, category: 'transition_metal', row: 5, col: 10, color: '#ff6b00' },
  { symbol: 'Ag', name: 'Silver', number: 47, mass: 107.87, category: 'transition_metal', row: 5, col: 11, color: '#ff6b00' },
  { symbol: 'Cd', name: 'Cadmium', number: 48, mass: 112.41, category: 'transition_metal', row: 5, col: 12, color: '#ff6b00' },
  { symbol: 'In', name: 'Indium', number: 49, mass: 114.82, category: 'post_transition', row: 5, col: 13, color: '#00ccff' },
  { symbol: 'Sn', name: 'Tin', number: 50, mass: 118.71, category: 'post_transition', row: 5, col: 14, color: '#00ccff' },
  { symbol: 'Sb', name: 'Antimony', number: 51, mass: 121.76, category: 'metalloid', row: 5, col: 15, color: '#00ff88' },
  { symbol: 'Te', name: 'Tellurium', number: 52, mass: 127.60, category: 'metalloid', row: 5, col: 16, color: '#00ff88' },
  { symbol: 'I', name: 'Iodine', number: 53, mass: 126.90, category: 'halogen', row: 5, col: 17, color: '#ffff00' },
  { symbol: 'Xe', name: 'Xenon', number: 54, mass: 131.29, category: 'noble_gas', row: 5, col: 18, color: '#b000ff' },
  // Period 6
  { symbol: 'Cs', name: 'Cesium', number: 55, mass: 132.91, category: 'alkali_metal', row: 6, col: 1, color: '#ff0040' },
  { symbol: 'Ba', name: 'Barium', number: 56, mass: 137.33, category: 'alkaline_earth', row: 6, col: 2, color: '#ff6b00' },
  { symbol: 'La', name: 'Lanthanum', number: 57, mass: 138.91, category: 'lanthanide', row: 9, col: 3, color: '#ff00ff' },
  { symbol: 'Ce', name: 'Cerium', number: 58, mass: 140.12, category: 'lanthanide', row: 9, col: 4, color: '#ff00ff' },
  { symbol: 'Pr', name: 'Praseodymium', number: 59, mass: 140.91, category: 'lanthanide', row: 9, col: 5, color: '#ff00ff' },
  { symbol: 'Nd', name: 'Neodymium', number: 60, mass: 144.24, category: 'lanthanide', row: 9, col: 6, color: '#ff00ff' },
  { symbol: 'Pm', name: 'Promethium', number: 61, mass: 145.00, category: 'lanthanide', row: 9, col: 7, color: '#ff00ff' },
  { symbol: 'Sm', name: 'Samarium', number: 62, mass: 150.36, category: 'lanthanide', row: 9, col: 8, color: '#ff00ff' },
  { symbol: 'Eu', name: 'Europium', number: 63, mass: 151.96, category: 'lanthanide', row: 9, col: 9, color: '#ff00ff' },
  { symbol: 'Gd', name: 'Gadolinium', number: 64, mass: 157.25, category: 'lanthanide', row: 9, col: 10, color: '#ff00ff' },
  { symbol: 'Tb', name: 'Terbium', number: 65, mass: 158.93, category: 'lanthanide', row: 9, col: 11, color: '#ff00ff' },
  { symbol: 'Dy', name: 'Dysprosium', number: 66, mass: 162.50, category: 'lanthanide', row: 9, col: 12, color: '#ff00ff' },
  { symbol: 'Ho', name: 'Holmium', number: 67, mass: 164.93, category: 'lanthanide', row: 9, col: 13, color: '#ff00ff' },
  { symbol: 'Er', name: 'Erbium', number: 68, mass: 167.26, category: 'lanthanide', row: 9, col: 14, color: '#ff00ff' },
  { symbol: 'Tm', name: 'Thulium', number: 69, mass: 168.93, category: 'lanthanide', row: 9, col: 15, color: '#ff00ff' },
  { symbol: 'Yb', name: 'Ytterbium', number: 70, mass: 173.05, category: 'lanthanide', row: 9, col: 16, color: '#ff00ff' },
  { symbol: 'Lu', name: 'Lutetium', number: 71, mass: 174.97, category: 'lanthanide', row: 9, col: 17, color: '#ff00ff' },
  { symbol: 'Hf', name: 'Hafnium', number: 72, mass: 178.49, category: 'transition_metal', row: 6, col: 4, color: '#ff6b00' },
  { symbol: 'Ta', name: 'Tantalum', number: 73, mass: 180.95, category: 'transition_metal', row: 6, col: 5, color: '#ff6b00' },
  { symbol: 'W', name: 'Tungsten', number: 74, mass: 183.84, category: 'transition_metal', row: 6, col: 6, color: '#ff6b00' },
  { symbol: 'Re', name: 'Rhenium', number: 75, mass: 186.21, category: 'transition_metal', row: 6, col: 7, color: '#ff6b00' },
  { symbol: 'Os', name: 'Osmium', number: 76, mass: 190.23, category: 'transition_metal', row: 6, col: 8, color: '#ff6b00' },
  { symbol: 'Ir', name: 'Iridium', number: 77, mass: 192.22, category: 'transition_metal', row: 6, col: 9, color: '#ff6b00' },
  { symbol: 'Pt', name: 'Platinum', number: 78, mass: 195.08, category: 'transition_metal', row: 6, col: 10, color: '#ff6b00' },
  { symbol: 'Au', name: 'Gold', number: 79, mass: 196.97, category: 'transition_metal', row: 6, col: 11, color: '#ff6b00' },
  { symbol: 'Hg', name: 'Mercury', number: 80, mass: 200.59, category: 'transition_metal', row: 6, col: 12, color: '#ff6b00' },
  { symbol: 'Tl', name: 'Thallium', number: 81, mass: 204.38, category: 'post_transition', row: 6, col: 13, color: '#00ccff' },
  { symbol: 'Pb', name: 'Lead', number: 82, mass: 207.20, category: 'post_transition', row: 6, col: 14, color: '#00ccff' },
  { symbol: 'Bi', name: 'Bismuth', number: 83, mass: 208.98, category: 'post_transition', row: 6, col: 15, color: '#00ccff' },
  { symbol: 'Po', name: 'Polonium', number: 84, mass: 209.00, category: 'post_transition', row: 6, col: 16, color: '#00ccff' },
  { symbol: 'At', name: 'Astatine', number: 85, mass: 210.00, category: 'halogen', row: 6, col: 17, color: '#ffff00' },
  { symbol: 'Rn', name: 'Radon', number: 86, mass: 222.00, category: 'noble_gas', row: 6, col: 18, color: '#b000ff' },
  // Period 7
  { symbol: 'Fr', name: 'Francium', number: 87, mass: 223.00, category: 'alkali_metal', row: 7, col: 1, color: '#ff0040' },
  { symbol: 'Ra', name: 'Radium', number: 88, mass: 226.00, category: 'alkaline_earth', row: 7, col: 2, color: '#ff6b00' },
  { symbol: 'Ac', name: 'Actinium', number: 89, mass: 227.00, category: 'actinide', row: 10, col: 3, color: '#ff4488' },
  { symbol: 'Th', name: 'Thorium', number: 90, mass: 232.04, category: 'actinide', row: 10, col: 4, color: '#ff4488' },
  { symbol: 'Pa', name: 'Protactinium', number: 91, mass: 231.04, category: 'actinide', row: 10, col: 5, color: '#ff4488' },
  { symbol: 'U', name: 'Uranium', number: 92, mass: 238.03, category: 'actinide', row: 10, col: 6, color: '#ff4488' },
  { symbol: 'Np', name: 'Neptunium', number: 93, mass: 237.00, category: 'actinide', row: 10, col: 7, color: '#ff4488' },
  { symbol: 'Pu', name: 'Plutonium', number: 94, mass: 244.00, category: 'actinide', row: 10, col: 8, color: '#ff4488' },
  { symbol: 'Am', name: 'Americium', number: 95, mass: 243.00, category: 'actinide', row: 10, col: 9, color: '#ff4488' },
  { symbol: 'Cm', name: 'Curium', number: 96, mass: 247.00, category: 'actinide', row: 10, col: 10, color: '#ff4488' },
  { symbol: 'Bk', name: 'Berkelium', number: 97, mass: 247.00, category: 'actinide', row: 10, col: 11, color: '#ff4488' },
  { symbol: 'Cf', name: 'Californium', number: 98, mass: 251.00, category: 'actinide', row: 10, col: 12, color: '#ff4488' },
  { symbol: 'Es', name: 'Einsteinium', number: 99, mass: 252.00, category: 'actinide', row: 10, col: 13, color: '#ff4488' },
  { symbol: 'Fm', name: 'Fermium', number: 100, mass: 257.00, category: 'actinide', row: 10, col: 14, color: '#ff4488' },
  { symbol: 'Md', name: 'Mendelevium', number: 101, mass: 258.00, category: 'actinide', row: 10, col: 15, color: '#ff4488' },
  { symbol: 'No', name: 'Nobelium', number: 102, mass: 259.00, category: 'actinide', row: 10, col: 16, color: '#ff4488' },
  { symbol: 'Lr', name: 'Lawrencium', number: 103, mass: 266.00, category: 'actinide', row: 10, col: 17, color: '#ff4488' },
  // Period 7 d-block
  { symbol: 'Rf', name: 'Rutherfordium', number: 104, mass: 267.00, category: 'transition_metal', row: 7, col: 4, color: '#ff6b00' },
  { symbol: 'Db', name: 'Dubnium', number: 105, mass: 268.00, category: 'transition_metal', row: 7, col: 5, color: '#ff6b00' },
  { symbol: 'Sg', name: 'Seaborgium', number: 106, mass: 269.00, category: 'transition_metal', row: 7, col: 6, color: '#ff6b00' },
  { symbol: 'Bh', name: 'Bohrium', number: 107, mass: 270.00, category: 'transition_metal', row: 7, col: 7, color: '#ff6b00' },
  { symbol: 'Hs', name: 'Hassium', number: 108, mass: 277.00, category: 'transition_metal', row: 7, col: 8, color: '#ff6b00' },
  { symbol: 'Mt', name: 'Meitnerium', number: 109, mass: 278.00, category: 'transition_metal', row: 7, col: 9, color: '#ff6b00' },
  { symbol: 'Ds', name: 'Darmstadtium', number: 110, mass: 281.00, category: 'transition_metal', row: 7, col: 10, color: '#ff6b00' },
  { symbol: 'Rg', name: 'Roentgenium', number: 111, mass: 282.00, category: 'transition_metal', row: 7, col: 11, color: '#ff6b00' },
  { symbol: 'Cn', name: 'Copernicium', number: 112, mass: 285.00, category: 'transition_metal', row: 7, col: 12, color: '#ff6b00' },
  { symbol: 'Nh', name: 'Nihonium', number: 113, mass: 286.00, category: 'post_transition', row: 7, col: 13, color: '#00ccff' },
  { symbol: 'Fl', name: 'Flerovium', number: 114, mass: 289.00, category: 'post_transition', row: 7, col: 14, color: '#00ccff' },
  { symbol: 'Mc', name: 'Moscovium', number: 115, mass: 290.00, category: 'post_transition', row: 7, col: 15, color: '#00ccff' },
  { symbol: 'Lv', name: 'Livermorium', number: 116, mass: 293.00, category: 'post_transition', row: 7, col: 16, color: '#00ccff' },
  { symbol: 'Ts', name: 'Tennessine', number: 117, mass: 294.00, category: 'halogen', row: 7, col: 17, color: '#ffff00' },
  { symbol: 'Og', name: 'Oganesson', number: 118, mass: 294.00, category: 'noble_gas', row: 7, col: 18, color: '#b000ff' },
];

export const ELEMENT_MAP: Record<ElementSymbol, ElementData> = Object.fromEntries(
  ELEMENTS.map(e => [e.symbol, e])
) as Record<ElementSymbol, ElementData>;

// Human body composition (% of body mass) — the 20 most significant elements
export const BODY_COMPOSITION: Record<ElementSymbol, number> = {
  O: 0.65,
  C: 0.185,
  H: 0.095,
  N: 0.032,
  Ca: 0.015,
  P: 0.010,
  K: 0.004,
  S: 0.003,
  Na: 0.002,
  Cl: 0.002,
  Mg: 0.001,
  Fe: 0.00006,
  Zn: 0.000032,
  Cu: 0.000001,
  Mn: 0.0000002,
  I: 0.0000002,
  Se: 0.0000001,
  Mo: 0.0000001,
  Co: 0.000000003,
  Cr: 0.000000003,
} as Record<ElementSymbol, number>;

// Fun facts about elements in your body
export const FUN_FACTS: { element: ElementSymbol; fact: string }[] = [
  { element: 'O', fact: 'Oxygen makes up 65% of your body — mostly locked in water molecules.' },
  { element: 'C', fact: 'You contain about 16 kg of carbon — enough to make 9,000 pencils.' },
  { element: 'H', fact: 'Your hydrogen atoms are 13.8 billion years old — forged in the Big Bang.' },
  { element: 'Fe', fact: 'You have enough iron to make a 3-inch nail (about 4 grams).' },
  { element: 'N', fact: 'The nitrogen in your DNA was once part of a star that went supernova.' },
  { element: 'Ca', fact: 'Your skeleton contains about 1 kg of calcium — 99% of your body\'s total.' },
  { element: 'P', fact: 'Phosphorus in your bones glows faintly — your skeleton is technically luminescent.' },
  { element: 'K', fact: 'The potassium in your body makes you slightly radioactive (~5,000 decays/second).' },
  { element: 'Au', fact: 'Your body contains ~0.2 mg of gold — mostly dissolved in your blood.' },
  { element: 'S', fact: 'Sulfur gives your hair and nails their strength via disulfide bonds.' },
  { element: 'Li', fact: 'Trace lithium in drinking water is linked to lower rates of depression.' },
  { element: 'Cu', fact: 'Copper gives your blood enzymes their blue-green color at the molecular level.' },
];
